// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTm7dRsBAdzOPJ9ZPp4A7oNZuWu-_JPq4',
    appId: '1:732037580334:android:80c16743be74479c6101bf',
    messagingSenderId: '732037580334',
    projectId: 'ball-lock',
    storageBucket: 'ball-lock.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhIuWJHcuCnnzklqgRjPP4XNBb1B70dG4',
    appId: '1:732037580334:ios:11f6ead295e3ccf46101bf',
    messagingSenderId: '732037580334',
    projectId: 'ball-lock',
    storageBucket: 'ball-lock.firebasestorage.app',
    iosBundleId: 'com.example.ball',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD66zc-XaM38g_T-XkYd2B-8-mRDbwcG8',
    appId: '1:732037580334:web:c8a57a71aa6c02a46101bf',
    messagingSenderId: '732037580334',
    projectId: 'ball-lock',
    authDomain: 'ball-lock.firebaseapp.com',
    storageBucket: 'ball-lock.firebasestorage.app',
    measurementId: 'G-WEP4KHQFFG',
  );

}